version: "3.9" 
volumes:
  data:
services:
  db:
    image: postgres:17-alpine
    container_name: docs-db 
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - postgres_net
networks:
  postgres_net:
    driver: bridge